# Python needed, so we use the python image.
image: python:latest

variables:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  PYFUNCEBLE_CONFIG_DIR: "$CI_PROJECT_DIR/.pyfunceble"
  PYFUNCEBLE_OUTPUT_LOCATION: "$CI_PROJECT_DIR/.pyfunceble"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip


before_script:
  # We install the development version of PyFunceble.
  # If you prefer the stable version replace `pyfunceble-dev`
  # with `pyfunceble`.
  - pip3 install PyFunceble mypdns

test1:
  stage: test
  script:
    # Let's say we want our results and our PyFunceble
    # infrastructure to be saved in a directory called `PyFunceble-tests`

    # We move inside it.
    - cd "$CI_PROJECT_DIR"
    - pyfunceble --syntax --no-files -f "$CI_PROJECT_DIR/source/adware/domains.list" "$CI_PROJECT_DIR/source/adware/wildcard.list" --ci-max-minutes 1
