env:
  global:
  - GIT_NAME: Travis CI
  - GIT_EMAIL: "44526987+spirillen@users.noreply.github.com"
  - secure: nhsYBlm5nQRhx+KTjRV+J7T3Ax252I8FG+Mz726FuQBvR0FEcg3dO57wlNcnKKS0Yh69srL6xxeJRv+7ZFH153QYQtcbzdpeK8aufGMmL1r6/SwQJ+Xge3EqzmQ+kIp5sS8wTzqckDt72TWPSBQXcY6RXbzo641XDl5WfemxN6fOmq+3IxCjlsgQUUfwTuEXHCwe6PuopUnDp5J6qbik7Gtf8ljfR6fwKTgqNAobHm9fpKbckb2foQrYIuAHe13zukgcMLe7OfpArIZjTXiWcGC7ftJZKSxRF7WqhXXT4WIQpCOlxlI+Dk1bwG0nfdEOAQKOIZjmPcYuloJ4UX99txSQNxMI7sWkLx8Z3NMpDjz6WYryLbqzepWQQJvllCsfBOpeXqFQDRHif3or+3pVU63vLOL770so8oWs0YM/OkifflnVhDCj4IdOhJ1SOrS5E8V5wrdhKnnnLxgsEOzMDz7VkEXgYMx6ezfjQtZurOYzxGqtWbtRSPaC7laKUDkg0ZNvent3HKo8IXxFbzZeaMfD3+hSjtrq7L90cgcnwQWslPNdpdgzK+abF7oRKu3pCEdq9W4ykK8+7/Ra7jPh/XsB/FwlDytKNAMrbEBENBojQ2zBBVGY/x7zaIrLQHuNMs7+My1DYiaL9meLuwgyQVAuV95ahRVdWCKWJIDGLV0=
  - GIT_BRANCH: master
  - TZ: UTC

addons:
  apt:
    packages:
    - dnsutils # Gives the dig
    - ldnsutils # Gives the drill

os: linux
dist: bionic
language: generic
git:
  depth: 2
branches:
  only:
  - master
matrix:
  fast_finish: true
script:
- bash $TRAVIS_BUILD_DIR/.travis/build.sh && bash $TRAVIS_BUILD_DIR/.travis/update_active_lists.sh
  && git add . && git commit -m 'Auto committed from the CI runner [ci skip]' && git
  push -u origin ${TRAVIS_BRANCH}
