cli_testing:
  autocontinue: true
  ci:
    autocontinue: true
    cidr_expand: true
    inactive-db: false
    active: true
    db_type: mariadb
    branch: master
    command: null
    commit_message: My Privacy DNS - Temp results
    distribution_branch: master
    end_command: null
    end_commit_message: My Privacy DNS - Results
    max_exec_minutes: 320
  days_between:
    db_clean: 120
  display_mode:
    all: false
    colour: true
    dots: true
    execution_time: true
    less: true
    percentage: true
    quiet: true
  file_generation:
    unified_results: true
  sorting_mode:
    hierarchical: true
dns:
  follow_server_order: true
  protocol: UDP
  server:
    - 9.9.9.10
user_agent:
  browser: firefox
  custom: null
  platform: linux
