name: Adult
description: Blacklist by My Privacy DNS
assignees:
  - spirillen
body:
  - type: checkboxes
    id: recordType
    attributes:
      label: Blacklist domain as
      description: How should we be blacklisting this domain?
      options:
      - label: Wildcard, The domain should be entirely blacklisted
      - label: Subdomain, We should not blacklist the entire domain, only sub-domains
      - label: Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

  - type: textarea
    id: domainRecords
    attributes:
      label: Domain records
      description: |
        List any records that needs to be blacklisted
        (comma separated CSV with pipes)
      placeholder: |
        example.com|category1,category2,category3
        *.example.com|category1,category2,category3
      render: CSV
    validations:
      required: true

  - type: textarea
    id: hostsRecords
    attributes:
      label: Hosts specific records, not used by DNS RPZ firewalls
      description: |
        Also tell us, what subdomains are required for RFC:952 and RFC:953
        (comma separated CSV with pipes)
      placeholder: |
        hosts.example.com
      render: CSS
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshot is required for committing domains, we can not visit all domains
      placeholder: |
        "![Screenshot of example.com](img-src)"
        **INFO**: You can copy paste images directly into this field.
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: logs from [uBlock Origin](https://github.com/gorhill/uBlock/)
      description: "Please paste your uBlock origin logs as table in markdown"
      placeholder: |
        <details><summary>Logger output</summary>

        | | | | | | | | |
        |:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
        | +2 | ##.Popover-message |  | github.com |  | post | dom | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +2 | \|\|collector.github.com^$1p,important | -- | github.com | 1 | post | xhr | `https://collector.github.com/github/collect` |

        </details>
    validations:
      required: false
