name: Adult
description: Submitting new porn domains
title: ''
labels: [ "NSFW Adult Material" ]
assignees:
  - spirillen

body:
  - type: markdown
    attributes:
      description: |
        Blacklist domain as
  - type: checkboxes
    id:

  - [ X ] [ Wildcarded ](source/porno-sites/wildcard.list)
  - [ ] [ Individual domain blocking ](source/porno-sites/domains.list)

      ```python
      example.org   CNAME . ; Adult
      *.example.org   CNAME . ; Adult
      ```

    ### additional for hosts
      ```shell

      www.
      ```

    ## Screenshots

      <details><Summary>Screenshot required</summary>



      </details>

  ## Logger output


  ### All Submissions:
  - [ x ] Have you followed the guidelines in our [Contributing](https://mypdns.org/w/contributing/) document?
  - [ x ] Have you checked to ensure there aren't other open [Merge Requests (MR)](/mypdns/matrix/pulls) or [Issues](../issues) for the same update/change?
  - [ x ] Added ScreenDump for prove of (False Negative)[https://mypdns.org/w/falsenegative/]

  ### Todo
  - [ x ] Added to Source file?
  - [ ] Added to the RPZ zone [adult.mypdns.cloud](https://mypdns.org/wiki/RpzList#adult) (@spirillen)
