name: Adult
description: Porn domain
labels: [ "NSFW Adult Material" ]
assignees:
  - spirillen
body:
  - type: checkboxes
    id: recordType
    attributes:
      label: Blacklist domain as
      description: How should we be blacklisting this domain?
      options:
      - label: Wildcard, The domain should be entirely blacklisted
      - label: By subdomain, We should not blacklist the entire domain, only sub-domains
      - label: Blacklist as both, category depended, How to Blacklisting depends on category assign per (sub-)domain

  - type: textarea
    id: domainRecords
    attributes:
      label: Domain records
      description: |
        List any records that needs to be blacklisted
        (comma separated CSV with pipes)
      placeholder: |
        example.com|category1,category2,category3
        *.example.com|category1,category2,category3
      render: CSV
    validations:
      required: true

  - type: textarea
    id: hostsRecords
    attributes:
      label: Hosts specific records, not used by DNS RPZ firewalls
      description: |
        Also tell us, what subdomains are required for RFC:952 and RFC:953
        (comma separated CSV with pipes)
      placeholder: |
        hosts.example.com
      render: CSS
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshot is required for committing domains, we can not visit all domains
      placeholder: |
        "![Screenshot of example.com](img-src)"
        **INFO**: You can copy paste images directly into this field.
      render: Markdown
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: logs from [uBlock Origin](https://github.com/gorhill/uBlock/)
      description: "Please paste your uBlock origin logs as table in markdown"
      placeholder: |
        <details><summary>Logger output</summary>

        | | | | | | | | |
        |:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
        | +2 | ##.Popover-message |  | github.com |  | post | dom | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +2 | \|\|collector.github.com^$1p,important | -- | github.com | 1 | post | xhr | `https://collector.github.com/github/collect` |
        | +1 | *$document,permissions=browsing-topics=(),from=~localhost | -- | github.com | 1 | get | doc | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +1 | *$document,permissions=idle-detection=(),from=~localhost | -- | github.com | 1 | get | doc | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +1 | *$document,permissions=join-ad-interest-group=(),from=~localhost | -- | github.com | 1 | get | doc | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +1 | *$document,permissions=run-ad-auction=(),from=~localhost | -- | github.com | 1 | get | doc | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +1 | *$document,permissions=attribution-reporting=(),from=~localhost | -- | github.com | 1 | get | doc | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +1 | no-remote-fonts: * true | -- | github.com | 1 | get | doc | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |
        | +1 | no-remote-fonts: * true | -- | github.com | 1 | get | inline-font | `https://github.com/mypdns/matrix/issues/new?assignees=spirillen&labels=NSFW+Adult+Material&projects=&template=adult.yml` |

        </details>
      render: Markdown
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: |
        By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/mypdns/matrix/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I agree to follow this project's contribution guidelines
          required: true
        - label: I have checked there are no other issues for this domain.
          required: true
