blank_issues_enabled: false
contact_links:
  - name: My Privacy DNS Community Support
    url: https://mypdns.org/MypDNS/support/
    about: Please ask and answer questions here.
  - name: AdWare
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=AdWare
    about: Report any AdWare domain here
  - name: Adult contents
    url: https://mypdns.org/my-privacy-dns/porn-records/-/issues/new?issue[issue_type]=issue&issuable_template=Adult%20contents
    about: Please report adult contents here.
  - name: Block DNS Server
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=DNS%20Server
    about: If you have found a DNS Server that is only is used for bad things or maybe only used for hosting domains in adult material
  - name: Gambling
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Gambling
    about: Report any gambling realted domains
  - name: Hijacked / Pirated / Sharked
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Pirated%20Domain
    about: Report any Hijacked or Pirated domain here.
  - name: IP Blocking
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new
    about: If you would like to report IP Blocking addresses to be blocked.Report by CIDR range (/xx).
  - name: Malicious
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Malicious%20MalWare
    about: Report any Malicious domains here
  - name: Redirecting
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Redirecting
    about: Any domains used explicit to redirect urls, Typically used as AdWare and Tracking at the same time
  - name: Scam / Spam
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Scamming%20Spam
    about: Any domain arises from spam or domain used for scamming like pretending to be a Microsoft supporter who have called you, laiming you have a lot of issues with your installation
  - name: SpyWare
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Spyware
    about: Report any kind of SpyWare here. SpyWare is a weird classification, TrackWare actually also is SpyWare and SpyWare is used for Tracking you.. The definition is therefor SpyWare is unwanted Tracking installed by software. E.g. Google OS, 360totalsecurity, Avast
  - name: Tracking
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Tracking
    about: Report any domain used for Tracking
  - name: Typo Squatting
    url: https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Typo Squatting
    about: Typo Squatting or Cyber Squatting domains
  - name: Other issues
    url: https://mypdns.org/MypDNS/support/-/issues/new
    about: If you have a issue or found a bug this is the place.
