name: Domain blacklist
description: Blacklist by My Privacy DNS
assignees:
  - spirillen
body:
  - type: checkboxes
    id: recordType
    attributes:
      label: Blacklist domain as
      description: How should we be blacklisting this domain?
      options:
        - label: Wildcard, The domain should be entirely blacklisted
        - label: Subdomain, We should not blacklist the entire domain, only sub-domains
        - label: Both types, category depended, How to Blacklist, depends on category assign per (sub-)domain

  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Add any comments
      placeholder: This hosting service is usual quick to fix phishing issues
    validations:
      required: false

  - type: textarea
    id: domainRecords
    attributes:
      label: Domain records
      description: |
        List any records that needs to be blacklisted (comma separated CSV with pipes)
      placeholder: |
        example.com|adware,tracking,adult
        *.example.com|adware,tracking,adult
      render: CSV
    validations:
      required: true

  - type: textarea
    id: hostsRecords
    attributes:
      label: Hosts specific records, not used by DNS RPZ firewalls
      description: |
        Also tell us, what subdomains are required for RFC:952 and RFC:953 - (comma separated CSV with pipes)
      placeholder: |
        dumb.hosts.file.example.com
      render: CSS
    validations:
      required: false

  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Screenshot is required for committing domains, we can not visit all domains. Type `N/A` if not impossible.
      placeholder: |
        "![Screenshot of example.com](img-src)"
        **INFO**: You can copy paste images directly into this field.
      value: |
        <details><summary>Screenshot</summary>


        </details>
    validations:
      required: true

  - type: textarea
    id: externalSource
    attributes:
      label: Links to external sources
      description: If you have any external info, that can help process this issue
      render: CSS
      value: |
        ```

        ```
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: logs from uBlock Origin
      description: 'Please paste your [uBlock origin](https://github.com/gorhill/uBlock/) logs as table in markdown'
      value: N/A
    validations:
      required: false
