name: "Test"
on:
  pull_request:
    types: [opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Send Review Request 1"
      if: github.actor == 'AnonymousPoster'
      uses: kunihiko-t/review-request-action@v0.1.3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: "spirillen"
        team-reviewers: "spirillen"
    - name: "Send Review Request 2"
      if: github.actor == 'spirillen'
      uses: kunihiko-t/review-request-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: "AnonymousPoster"
        team-reviewers: "spirillen"
